---
- name: My Super Puper Playbook for Variables Lesson
  hosts: all
  become: yes


  vars:
    message1: Privet
    message2: World
    secret: XASDGSDFG

  tasks:

  - name: Print Secret variable
    debug:
      var: secret

  - debug:
      msg: "secretnoe slova {{ secret }}"

  - debug:
      msg: "Vladelec Etogo Servera -->{{ owner }}<--"

  - set_fact: full_message="{{ message1 }} {{ message2 }} from {{ owner }} "

  - debug:
      var: full_message

  - debug:
      var: ansible_distribution

  - shell: uptime
    register: results

  - debug:
      var: results

  - debug:
      var: results.stdout

